# Generated by Django 4.0.2 on 2022-03-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artistprofilebulkupload_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofilebulkupload',
            old_name='csv_file',
            new_name='file',
        ),
    ]
