# Generated by Django 4.0.2 on 2022-03-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_rename_csv_file_artistprofilebulkupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistalias',
            name='alias',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
